name: checks
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install cpplint
      - run: cpplint --recursive .
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install pylint
      - run: find . -type f -name "*.py" | xargs pylint
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: create build directory
        run: mkdir build
      - name: generate build files
        working-directory: build
        run: cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: build
        working-directory: build
        run: make
      - name: test
        working-directory: build
        run: ./bin/tests.out
