name: checks
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install cpplint
      - run: cpplint --recursive ai/src ai/tests
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pylint
      - run: find api/src -type f -name "*.py" | xargs pylint
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: create hyperparameters file
        run: cp ai/src/mccfr/hyperparameters.h.dev ai/src/mccfr/hyperparameters.h
      - name: build
        run: docker build -t fishbait-ai ./ai
      - name: test
        run: docker run --rm fishbait-ai /build/bin/tests.out
